let specify the full 'path' for FontAwesome fonts
aesmail/kaffy pull request #186
Opened 2020-11-30 17:59 UTC by manuel-rubio

Because FontAwesome is using different prefixes (https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use): fas, fab, far, fad and fal; I've made an addition to the specification for tidbit and widgets to let us use `full_icon` and specify, i.e. `fab fa-google-play`

2020-12-22 18:57 UTC, aesmail requested changes
Great work. You only need to fix the minor issue before this could be merged.

2020-12-22 18:57 UTC, aesmail commented on lib/kaffy_web/templates/layout/app.html.eex
> +                  <i class="<%= if custom_link.full_icon do %><%= custom_link[:full_icon] %><% else %>fas fa-<%= custom_link.icon %><% end %> menu-icon"></i>
This needs to be `if custom_link[:full_icon]` instead of `if custom_link.full_icon` since it might not be assigned and it doesn't have a default value. The PR will be ready to merge once this is fixed 👍🏼

2020-12-22 22:22 UTC, manuel-rubio commented on lib/kaffy_web/templates/layout/app.html.eex
> +                  <i class="<%= if custom_link.full_icon do %><%= custom_link[:full_icon] %><% else %>fas fa-<%= custom_link.icon %><% end %> menu-icon"></i>
done

2023-04-12 15:57 UTC, ghenry commented
Hi,

Would you be so kind as to do this again to the master branch?

Thanks,
Gavin.

2023-04-28 12:51 UTC, manuel-rubio commented
@ghenry it's rebased, it's still pending @aesmail press merge button ;-)

2023-04-28 13:26 UTC, merged